### ISSUE TITLE
Raising djangos ImproperlyConfigured Exception fails silently

### ISSUE THREAD

**Issue by stefanfoulis** [schwuk/django-getenv#4]
Django tends to silently swallow an ``ImproperlyConfigured`` exception when loading ``settings.py``. This can cause non-obvious bugs where everything in ``settings.py`` is ignored after a ``env('MYVAR', required=True)`` that throws that exception if MYVAR is not set.

I propose always raising the custom ``ImproperlyConfigured`` exception to avoid this problem.

**Comment by stefanfoulis** [comment]
@schwuk Do you agree with my reasoning? If yes I'll make a PR for you to review :-)

**Comment by schwuk** [comment]
That sounds great @stefanfoulis!
